version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mental-health-postgres
    environment:
      POSTGRES_DB: mental_health_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 231220
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mental-health-network

  minio:
    image: minio/minio:latest
    container_name: mental-health-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - mental-health-network

  mental-health-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mental-health-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    networks:
      - mental-health-network
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:

networks:
  mental-health-network:
    driver: bridge